//SBC dashboard constants
export const GET_SBC_DATA_REQUEST = 'GET_SBC_DATA_REQUEST';
export const GET_SBC_DATA_SUCCESS = 'GET_SBC_DATA_SUCCESS';
export const GET_SBC_DATA_FAILURE = 'GET_SBC_DATA_FAILURE';

//Email dashboard constants
export const GET_EMAIL_DATA_REQUEST = 'GET_EMAIL_DATA_REQUEST';
export const GET_EMAIL_DATA_SUCCESS = 'GET_EMAIL_DATA_SUCCESS';
export const GET_EMAIL_DATA_FAILURE = 'GET_EMAIL_DATA_FAILURE';

//Email dashboard scheduler list constant
export const GET_EMAIL_SCHEDULER_DATA_REQUEST = 'GET_EMAIL_SCHEDULAR_DATA_REQUEST'
export const GET_EMAIL_SCHEDULER_DATA_SUCCESS = 'GET_EMAIL_SCHEDULAR_DATA_SUCCESS'
export const GET_EMAIL_SCHEDULER_DATA_FAILURE = 'GET_EMAIL_SCHEDULAR_DATA_FAILURE'

//Email dashboard disabled period list constant
export const GET_EMAIL_DISABLED_PERIOD_REQUEST = 'GET_EMAIL_DISABLED_PERIOD_REQUEST'
export const GET_EMAIL_DISABLED_PERIOD_SUCCESS = 'GET_EMAIL_DISABLED_PERIOD_SUCCESS'
export const GET_EMAIL_DISABLED_PERIOD_FAILURE = 'GET_EMAIL_DISABLED_PERIOD_FAILURE'
